/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR        0x40023800UL
#define RCC_CFGR_REG_OFFSET  0x08UL
#define RCC_CFGR_REG_ADDR	 ((RCC_CFGR_REG_OFFSET) + (RCC_BASE_ADDR));

#define GPIOA_BASE_ADDR      0x40020000

int main(void)
{
	uint32_t* pRccCfgrReg = (uint32_t*) RCC_CFGR_REG_ADDR;

	//Clear bit 21 and 22 to set HSI as clock source
	*pRccCfgrReg &= ~(1 << 21);
	*pRccCfgrReg &= ~(1 << 22);

	//Set PA8 to AF0 mode to act as MC01 signal
	uint32_t* pRccAhb1Enr = (uint32_t*) (RCC_BASE_ADDR + 0x30);
	*pRccAhb1Enr |= (1 << 0); //Enables GPIOA Peripheral Clock

	//Configure mode of GPIOA pin 8 to alternate function mode
	uint32_t* pGPIOAModeReg = (uint32_t*) (GPIOA_BASE_ADDR);
	*pGPIOAModeReg &= (0x3 << 16); //Clear
	*pGPIOAModeReg |= (0x2 << 16); //Set

	//Configure alternate function register to set mode to 0 for PA8
	uint32_t *pGPIOAAltFunHighReg = (uint32_t*) (GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= (0xf << 0);



    /* Loop forever */
	for(;;);
}
